title: Jonathan Green's Website
author: GitHub User
theme: minima
email: Jgreen4@ebnet.org
description: I like to sell shoes, and make money. I occasionally study but that really is not my thing. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
